[package]
name = "x-auto-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
udev = "0.7"
nix = "0.26"
x11rb = { version = "0.11", features = [ "randr" ] }
